displayName=Object Markers Plus
authors=Krak
description=Share, Import & Export Object Markers
tags= Object, Markers, Plus, import, export
version=1
plugins=com.objectmarkerplus.ObjectMarkerPlugin
build=standard