displayName=Object Markers Plus
author=Krak
description=Share, Import & Export Object Markers
tags= Object, Markers, Plus, import, export
plugins=com.objectmarkerplus.ObjectMarkerPlugin
build=standard